//!Important: Here we will code all of the following methods in our CafeUtil.java file.

public class CafeUtil{
    public int getStreakGoal(){
        //work on method later
        return 10;
    }

    public double getOrderTotal(double[] prices){
        //work on method later
        return 1.99
    }

    public void displayMenu(ArrayList<String> menuItems){
        //work on method later
    }

    public void addCustomer(ArrayList<String> customers){
        //work on method later
    }




}
